laminas:
  build: .
  dockerfile: Dockerfile
  ports:
    - "8080:80"
  volumes:
    - .:/var/www

mysql:
  image: mysql:latest
  container_name: mysql8
  volumes:
    - my-datavolume:/var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: rPass1231
    MYSQL_DATABASE: revelations_log
    MYSQL_USER: uRevelations
    MYSQL_PASSWORD: uPass1231
#volumes:
#  my-datavolume: